spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 973e67deaae892c9675e
            client-secret: 6c2a873b230754a3ac2a6460393159d24f668477

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
